[package]
name = "gunz"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false
default-run = "gunz"

[dependencies]
bevy = { version = "0.19", features = ["dds", "bmp", "tga", "jpeg", "wav"] }
flate2 = "1"
roxmltree = "0.21"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
